- ansible.builtin.debug: 
    var: item

- name: Execute show command
  cisco.ios.ios_command:
    commands: "{{ item }}"
  register: output

- ansible.builtin.debug: 
    var: output

- name: Convert show command to proper file name
  ansible.builtin.set_fact:
    file_name: "{{ item | regex_replace(' ', '_') }}.txt"

- ansible.builtin.debug: 
    msg: "{{ ansible_host }}/{{ stage }}/{{ file_name }}"

- name: Save show output
  ansible.builtin.copy:
    content: "{{ output.stdout[0] }}"
    dest: "{{ ansible_host }}/{{ stage }}/{{ file_name }}"
