---
- hosts: cisco
  name: Gather output of show commands
  gather_facts: False
  tasks:
  - name: Create the directories
    import_tasks: create_dirs.yml

  - name: Execute show commands
    include_tasks: info_gather.yml
    loop:
      - show version
      - show ip int brief
      - show interfaces

